# Generated by Django 4.2.2 on 2023-06-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countCalorie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="food",
            old_name="calorie",
            new_name="calories",
        ),
    ]
